<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk;

use Illuminate\Support\Carbon;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

/**
 * Runtime narrowing for wire values.
 *
 * @internal generated support code — throws UnexpectedResponseException when the API response does not match the OpenAPI spec.
 */
final class Cast
{
    /**
     * @throws UnexpectedResponseException
     */
    public static function toString(mixed $value, string $path = ''): string
    {
        if (is_string($value)) {
            return $value;
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        self::fail('string', $value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toStringOrNull(mixed $value, string $path = ''): ?string
    {
        return $value === null ? null : self::toString($value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toInt(mixed $value, string $path = ''): int
    {
        if (is_int($value)) {
            return $value;
        }

        // Integral numeric strings ("42", "42.0") coerce; "12.7" or "abc" throw.
        if (is_string($value) && is_numeric($value)) {
            $int = (int) $value;
            if ((string) $int === $value || (float) $value === (float) $int) {
                return $int;
            }
        }

        if (is_float($value) && $value === (float) (int) $value) {
            return (int) $value;
        }

        self::fail('int', $value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toIntOrNull(mixed $value, string $path = ''): ?int
    {
        return $value === null ? null : self::toInt($value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toFloat(mixed $value, string $path = ''): float
    {
        if (is_float($value) || is_int($value)) {
            return $value;
        }

        if (is_string($value) && is_numeric($value)) {
            return (float) $value;
        }

        self::fail('float', $value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toFloatOrNull(mixed $value, string $path = ''): ?float
    {
        return $value === null ? null : self::toFloat($value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toBool(mixed $value, string $path = ''): bool
    {
        if (is_bool($value)) {
            return $value;
        }

        if ($value === 0 || $value === '0' || $value === 'false') {
            return false;
        }

        if ($value === 1 || $value === '1' || $value === 'true') {
            return true;
        }

        self::fail('bool', $value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toBoolOrNull(mixed $value, string $path = ''): ?bool
    {
        return $value === null ? null : self::toBool($value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toDate(mixed $value, string $path = ''): Carbon
    {
        $string = self::toString($value, $path);

        // Carbon::parse() turns '' into now() and zero-dates into nonsense — both
        // are legacy-DB idioms for "no date", so they must fail, not fabricate.
        if (trim($string) === '' || str_starts_with($string, '0000-00-00')) {
            self::fail('parseable date', $value, $path);
        }

        try {
            return Carbon::parse($string);
        } catch (\InvalidArgumentException) { // Carbon's InvalidFormatException extends this
            self::fail('parseable date', $value, $path);
        }
    }

    /**
     * @throws UnexpectedResponseException
     */
    public static function toDateOrNull(mixed $value, string $path = ''): ?Carbon
    {
        return $value === null ? null : self::toDate($value, $path);
    }

    /**
     * @return array<array-key, mixed>
     *
     * @throws UnexpectedResponseException
     */
    public static function toArray(mixed $value, string $path = ''): array
    {
        if (is_array($value)) {
            return $value;
        }

        self::fail('array', $value, $path);
    }

    /**
     * @return list<mixed>
     *
     * @throws UnexpectedResponseException
     */
    public static function toList(mixed $value, string $path = ''): array
    {
        return array_values(self::toArray($value, $path));
    }

    /**
     * @template T of \BackedEnum
     *
     * @param  class-string<T>  $enumClass
     * @return T
     *
     * @throws UnexpectedResponseException
     */
    public static function toEnum(mixed $value, string $enumClass, string $path = ''): \BackedEnum
    {
        // Compare stringified backing values so int-backed enums accept numeric
        // strings and string-backed enums accept ints — tryFrom() would TypeError.
        $string = self::toString($value, $path);

        foreach ($enumClass::cases() as $case) {
            if ((string) $case->value === $string) {
                return $case;
            }
        }

        self::fail('one of ['.implode(', ', array_map(static fn (\BackedEnum $c): string => (string) $c->value, $enumClass::cases())).']', $value, $path);
    }

    /**
     * @return array<string, mixed>
     *
     * @throws UnexpectedResponseException
     */
    public static function toMap(mixed $value, string $path = ''): array
    {
        $out = [];
        foreach (self::toArray($value, $path) as $key => $item) {
            $out[(string) $key] = $item;
        }

        return $out;
    }

    /**
     * @return array<string, mixed>|null
     *
     * @throws UnexpectedResponseException
     */
    public static function toMapOrNull(mixed $value, string $path = ''): ?array
    {
        return $value === null ? null : self::toMap($value, $path);
    }

    /**
     * @return array<string, string>
     *
     * @throws UnexpectedResponseException
     */
    public static function toStringMap(mixed $value, string $path = ''): array
    {
        $out = [];
        foreach (self::toArray($value, $path) as $key => $item) {
            $out[(string) $key] = self::toString($item, $path.'['.$key.']');
        }

        return $out;
    }

    /**
     * @return array<string, string>|null
     *
     * @throws UnexpectedResponseException
     */
    public static function toStringMapOrNull(mixed $value, string $path = ''): ?array
    {
        return $value === null ? null : self::toStringMap($value, $path);
    }

    /**
     * @return array<string, int>
     *
     * @throws UnexpectedResponseException
     */
    public static function toIntMap(mixed $value, string $path = ''): array
    {
        $out = [];
        foreach (self::toArray($value, $path) as $key => $item) {
            $out[(string) $key] = self::toInt($item, $path.'['.$key.']');
        }

        return $out;
    }

    /**
     * @return array<string, int>|null
     *
     * @throws UnexpectedResponseException
     */
    public static function toIntMapOrNull(mixed $value, string $path = ''): ?array
    {
        return $value === null ? null : self::toIntMap($value, $path);
    }

    /**
     * @return array<string, float>
     *
     * @throws UnexpectedResponseException
     */
    public static function toFloatMap(mixed $value, string $path = ''): array
    {
        $out = [];
        foreach (self::toArray($value, $path) as $key => $item) {
            $out[(string) $key] = self::toFloat($item, $path.'['.$key.']');
        }

        return $out;
    }

    /**
     * @return array<string, float>|null
     *
     * @throws UnexpectedResponseException
     */
    public static function toFloatMapOrNull(mixed $value, string $path = ''): ?array
    {
        return $value === null ? null : self::toFloatMap($value, $path);
    }

    /**
     * @return array<string, bool>
     *
     * @throws UnexpectedResponseException
     */
    public static function toBoolMap(mixed $value, string $path = ''): array
    {
        $out = [];
        foreach (self::toArray($value, $path) as $key => $item) {
            $out[(string) $key] = self::toBool($item, $path.'['.$key.']');
        }

        return $out;
    }

    /**
     * @return array<string, bool>|null
     *
     * @throws UnexpectedResponseException
     */
    public static function toBoolMapOrNull(mixed $value, string $path = ''): ?array
    {
        return $value === null ? null : self::toBoolMap($value, $path);
    }

    /**
     * @throws UnexpectedResponseException
     */
    private static function fail(string $expected, mixed $value, string $path): never
    {
        throw new UnexpectedResponseException(
            ($path === '' ? '' : $path.': ').'expected '.$expected.', got '.get_debug_type($value)
        );
    }
}
