<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk;

/**
 * Sentinel for "field not provided" in partial-update request DTOs.
 *
 * Distinguishes omitting a field entirely (server leaves it untouched)
 * from sending an explicit null (server clears it).
 */
enum Omitted
{
    case Value;
}
