<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk;

use Illuminate\Container\Attributes\Config;
use Illuminate\Container\Attributes\Singleton;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;
use Orbit\Sdk\Exceptions\ConfigurationException;
use Orbit\Sdk\Resources\BeaconsResource;
use Orbit\Sdk\Resources\TelemetryResource;

/**
 * Client for Orbit (spec version 2.0.0).
 *
 * Resolve via the container — `app(OrbitClient::class)` — to read
 * config('services.orbit.url'), .api_key, .timeout (seconds) and .retries,
 * or construct explicitly with make() / fromPendingRequest().
 *
 * When config('services.orbit.url') is absent, the base URL defaults to the
 * spec's declared server: https://api.example.com/v1
 */
#[Singleton]
final class OrbitClient
{
    public const API_KEY_HEADER = 'Authorization';

    private ?PendingRequest $http = null;

    public function __construct(
        #[Config('services.orbit.url', 'https://api.example.com/v1')]
        private string $baseUrl = 'https://api.example.com/v1',
        #[Config('services.orbit.api_key', null)]
        private ?string $apiKey = null,
        #[Config('services.orbit.timeout', null)]
        private ?int $timeout = null,
        #[Config('services.orbit.retries', null)]
        private ?int $retries = null,
    ) {}

    public static function make(
        string $baseUrl = 'https://api.example.com/v1',
        ?string $apiKey = null,
        ?int $timeout = null,
        ?int $retries = null,
    ): self {
        return new self($baseUrl, $apiKey, $timeout, $retries);
    }

    /**
     * Bring your own PendingRequest — base URL, auth, middleware, fakes.
     */
    public static function fromPendingRequest(PendingRequest $http): self
    {
        $client = new self;
        $client->http = $http;

        return $client;
    }

    /**
     * The underlying PendingRequest (built lazily from config on first use).
     */
    public function http(): PendingRequest
    {
        if ($this->http !== null) {
            return $this->http;
        }

        if ($this->baseUrl === '') {
            throw new ConfigurationException('OrbitClient has no base URL. Set config(\'services.orbit.url\') (config/services.php + .env) or pass a base URL to OrbitClient::make().');
        }

        $http = Http::baseUrl(rtrim($this->baseUrl, '/'))->acceptJson()->asJson();

        if ($this->apiKey !== null) {
            $http = $http->withToken($this->apiKey);
        }

        if ($this->timeout !== null) {
            $http = $http->timeout($this->timeout);
        }

        if ($this->retries !== null) {
            $http = $http->retry($this->retries, 100);
        }

        return $this->http = $http;
    }

    public function beacons(): BeaconsResource
    {
        return new BeaconsResource($this->http());
    }

    public function telemetry(): TelemetryResource
    {
        return new TelemetryResource($this->http());
    }
}
