<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Dto;

use Gizmo\Sdk\Cast;
use Gizmo\Sdk\Exceptions\UnexpectedResponseException;

final readonly class Assembly implements \JsonSerializable
{
    /**
     * @param  int|null  $recAssemblySN  [__rec_AssemblySN] Assembly serial number
     * @param  string|null  $assemblyName  [assembly_name] Line name
     * @param  int|null  $stationCount  [station_count] Number of stations on the line
     */
    public function __construct(
        public ?int $recAssemblySN = null,
        public ?string $assemblyName = null,
        public ?int $stationCount = null,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            recAssemblySN: Cast::toIntOrNull($data['__rec_AssemblySN'] ?? null, 'Assembly.__rec_AssemblySN'),
            assemblyName: Cast::toStringOrNull($data['assembly_name'] ?? null, 'Assembly.assembly_name'),
            stationCount: Cast::toIntOrNull($data['station_count'] ?? null, 'Assembly.station_count'),
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        if ($this->recAssemblySN !== null) {
            $out['__rec_AssemblySN'] = $this->recAssemblySN;
        }
        if ($this->assemblyName !== null) {
            $out['assembly_name'] = $this->assemblyName;
        }
        if ($this->stationCount !== null) {
            $out['station_count'] = $this->stationCount;
        }

        return $out;
    }
}
