<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Dto;

use Gizmo\Sdk\Omitted;

final readonly class WidgetUpdate implements \JsonSerializable
{
    /**
     * @param  Omitted|string|null  $widgetName  [widget_name] Display name
     * @param  Omitted|string|null  $binLocation  [bin_location] Warehouse bin
     * @param  Omitted|string|null  $calcAssemblyCodeID  [calc_AssemblyCodeID] Assembly code
     */
    public function __construct(
        public Omitted|string|null $widgetName = Omitted::Value,
        public Omitted|string|null $binLocation = Omitted::Value,
        public Omitted|string|null $calcAssemblyCodeID = Omitted::Value,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        if (! $this->widgetName instanceof Omitted) {
            $out['widget_name'] = $this->widgetName;
        }
        if (! $this->binLocation instanceof Omitted) {
            $out['bin_location'] = $this->binLocation;
        }
        if (! $this->calcAssemblyCodeID instanceof Omitted) {
            $out['calc_AssemblyCodeID'] = $this->calcAssemblyCodeID;
        }

        return $out;
    }
}
