<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Dto;

use Gizmo\Sdk\Cast;
use Gizmo\Sdk\Exceptions\UnexpectedResponseException;
use Illuminate\Support\Carbon;

final readonly class Widget implements \JsonSerializable
{
    /**
     * @param  int|null  $recWidgetSN  [__rec_WidgetSN] Widget serial number (primary key)
     * @param  string|null  $calcAssemblyCodeID  [calc_AssemblyCodeID] Assembly code (calculated)
     * @param  string|null  $widgetName  [widget_name] Display name
     * @param  string|null  $binLocation  [bin_location] Warehouse bin
     * @param  Carbon|null  $builtAt  [built_at] Build timestamp
     */
    public function __construct(
        public ?int $recWidgetSN = null,
        public ?string $calcAssemblyCodeID = null,
        public ?string $widgetName = null,
        public ?string $binLocation = null,
        public ?Carbon $builtAt = null,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            recWidgetSN: Cast::toIntOrNull($data['__rec_WidgetSN'] ?? null, 'Widget.__rec_WidgetSN'),
            calcAssemblyCodeID: Cast::toStringOrNull($data['calc_AssemblyCodeID'] ?? null, 'Widget.calc_AssemblyCodeID'),
            widgetName: Cast::toStringOrNull($data['widget_name'] ?? null, 'Widget.widget_name'),
            binLocation: Cast::toStringOrNull($data['bin_location'] ?? null, 'Widget.bin_location'),
            builtAt: Cast::toDateOrNull($data['built_at'] ?? null, 'Widget.built_at'),
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        if ($this->recWidgetSN !== null) {
            $out['__rec_WidgetSN'] = $this->recWidgetSN;
        }
        if ($this->calcAssemblyCodeID !== null) {
            $out['calc_AssemblyCodeID'] = $this->calcAssemblyCodeID;
        }
        if ($this->widgetName !== null) {
            $out['widget_name'] = $this->widgetName;
        }
        if ($this->binLocation !== null) {
            $out['bin_location'] = $this->binLocation;
        }
        if ($this->builtAt !== null) {
            $out['built_at'] = $this->builtAt->toIso8601String();
        }

        return $out;
    }
}
