<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Dto;

use Illuminate\Support\Carbon;
use Orbit\Sdk\Cast;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class Beacon implements \JsonSerializable
{
    /**
     * @param  string  $callsign  Unique transmit callsign
     * @param  bool|null  $active  Currently transmitting
     * @param  Carbon|null  $launchedAt  [launched_at]
     * @param  GeoFix|null  $lastFix  [last_fix]
     */
    public function __construct(
        public int $id,
        public string $callsign,
        public ?bool $active = null,
        public ?Carbon $launchedAt = null,
        public ?GeoFix $lastFix = null,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: Cast::toInt($data['id'] ?? null, 'Beacon.id'),
            callsign: Cast::toString($data['callsign'] ?? null, 'Beacon.callsign'),
            active: Cast::toBoolOrNull($data['active'] ?? null, 'Beacon.active'),
            launchedAt: Cast::toDateOrNull($data['launched_at'] ?? null, 'Beacon.launched_at'),
            lastFix: isset($data['last_fix']) ? GeoFix::fromArray(Cast::toArray($data['last_fix'], 'Beacon.last_fix')) : null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        $out['id'] = $this->id;
        $out['callsign'] = $this->callsign;
        if ($this->active !== null) {
            $out['active'] = $this->active;
        }
        if ($this->launchedAt !== null) {
            $out['launched_at'] = $this->launchedAt->toIso8601String();
        }
        if ($this->lastFix !== null) {
            $out['last_fix'] = $this->lastFix;
        }

        return $out;
    }
}
