<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Dto;

use Orbit\Sdk\Cast;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class Error implements \JsonSerializable
{
    /**
     * @param  string  $code  Machine-readable error code
     * @param  string  $message  Human-readable explanation
     */
    public function __construct(
        public string $code,
        public string $message,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            code: Cast::toString($data['code'] ?? null, 'Error.code'),
            message: Cast::toString($data['message'] ?? null, 'Error.message'),
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        $out['code'] = $this->code;
        $out['message'] = $this->message;

        return $out;
    }
}
