<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Dto;

use Orbit\Sdk\Cast;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class GeoFix implements \JsonSerializable
{
    public function __construct(
        public float $lat,
        public float $lon,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            lat: Cast::toFloat($data['lat'] ?? null, 'GeoFix.lat'),
            lon: Cast::toFloat($data['lon'] ?? null, 'GeoFix.lon'),
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        $out['lat'] = $this->lat;
        $out['lon'] = $this->lon;

        return $out;
    }
}
