<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Dto;

use Illuminate\Support\Carbon;
use Orbit\Sdk\Enums\LaunchPlanCadence;
use Orbit\Sdk\Omitted;

final readonly class LaunchPlan implements \JsonSerializable
{
    /**
     * @param  string  $callsign  Requested transmit callsign
     * @param  LaunchPlanCadence  $cadence  Reporting cadence
     * @param  Omitted|Carbon|null  $windowStart  [window_start] Earliest acceptable launch window
     */
    public function __construct(
        public string $callsign,
        public LaunchPlanCadence $cadence,
        public Omitted|Carbon|null $windowStart = Omitted::Value,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        $out['callsign'] = $this->callsign;
        $out['cadence'] = $this->cadence;
        if (! $this->windowStart instanceof Omitted) {
            $out['window_start'] = $this->windowStart?->toIso8601String();
        }

        return $out;
    }
}
