<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Dto;

use Illuminate\Support\Carbon;
use Orbit\Sdk\Cast;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class TelemetrySnapshotResponse implements \JsonSerializable
{
    /**
     * @param  Carbon|null  $sampledAt  [sampled_at]
     * @param  float|null  $batteryPct  [battery_pct]
     */
    public function __construct(
        public ?Carbon $sampledAt = null,
        public ?float $batteryPct = null,
        public ?TelemetrySnapshotResponseSignal $signal = null,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            sampledAt: Cast::toDateOrNull($data['sampled_at'] ?? null, 'TelemetrySnapshotResponse.sampled_at'),
            batteryPct: Cast::toFloatOrNull($data['battery_pct'] ?? null, 'TelemetrySnapshotResponse.battery_pct'),
            signal: isset($data['signal']) ? TelemetrySnapshotResponseSignal::fromArray(Cast::toArray($data['signal'], 'TelemetrySnapshotResponse.signal')) : null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        if ($this->sampledAt !== null) {
            $out['sampled_at'] = $this->sampledAt->toIso8601String();
        }
        if ($this->batteryPct !== null) {
            $out['battery_pct'] = $this->batteryPct;
        }
        if ($this->signal !== null) {
            $out['signal'] = $this->signal;
        }

        return $out;
    }
}
