<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Dto;

use Orbit\Sdk\Cast;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class TelemetrySnapshotResponseSignal implements \JsonSerializable
{
    /**
     * @param  float|null  $strengthDb  [strength_db]
     */
    public function __construct(
        public ?float $strengthDb = null,
        public ?bool $locked = null,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            strengthDb: Cast::toFloatOrNull($data['strength_db'] ?? null, 'TelemetrySnapshotResponseSignal.strength_db'),
            locked: Cast::toBoolOrNull($data['locked'] ?? null, 'TelemetrySnapshotResponseSignal.locked'),
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        if ($this->strengthDb !== null) {
            $out['strength_db'] = $this->strengthDb;
        }
        if ($this->locked !== null) {
            $out['locked'] = $this->locked;
        }

        return $out;
    }
}
