<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Dto;

use Orbit\Sdk\Cast;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class UsageReport implements \JsonSerializable
{
    /**
     * @param  int  $total  Total messages this cycle
     * @param  array<string, int>|null  $counts  Message counts keyed by channel
     */
    public function __construct(
        public int $total,
        public ?array $counts = null,
    ) {}

    /**
     * @param  array<array-key, mixed>  $data
     *
     * @throws UnexpectedResponseException when the payload does not match the spec
     */
    public static function fromArray(array $data): self
    {
        return new self(
            total: Cast::toInt($data['total'] ?? null, 'UsageReport.total'),
            counts: Cast::toIntMapOrNull($data['counts'] ?? null, 'UsageReport.counts'),
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];

        $out['total'] = $this->total;
        if ($this->counts !== null) {
            $out['counts'] = $this->counts;
        }

        return $out;
    }
}
