<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Resources;

use Illuminate\Http\Client\Response;
use Illuminate\Support\Collection;
use Orbit\Sdk\Cast;
use Orbit\Sdk\Dto\Beacon;
use Orbit\Sdk\Dto\LaunchPlan;
use Orbit\Sdk\Exceptions\ConnectionException;
use Orbit\Sdk\Exceptions\RequestException;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class BeaconsResource extends Resource
{
    /**
     * List beacons
     *
     * GET /beacons
     *
     * @param  bool|null  $active  Only beacons currently transmitting
     * @return Collection<int, Beacon>
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function listBeacons(?bool $active = null): Collection
    {
        $query = array_filter([
            'active' => $active === null ? null : ($active ? '1' : '0'),
        ], static fn (mixed $value): bool => $value !== null);

        $response = $this->send(fn (): Response => $this->http->get('/beacons', $query));
        $data = Cast::toList($response->json() ?? [], 'listBeacons response');

        return (new Collection($data))->map(static fn (mixed $item): Beacon => Beacon::fromArray(Cast::toArray($item, 'listBeacons response[]')));
    }

    /**
     * Register a beacon from a launch plan
     *
     * POST /beacons
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function createBeacon(LaunchPlan $body): Beacon
    {
        $response = $this->send(fn (): Response => $this->http->post('/beacons', $body->jsonSerialize()));

        return Beacon::fromArray(Cast::toArray($response->json(), 'createBeacon response'));
    }

    /**
     * Fetch a beacon
     *
     * GET /beacons/{id}
     *
     * @param  int  $id  Beacon id
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function getBeacon(int $id): Beacon
    {
        $response = $this->send(fn (): Response => $this->http->get('/beacons/'.$id));

        return Beacon::fromArray(Cast::toArray($response->json(), 'getBeacon response'));
    }
}
