<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Resources;

use Closure;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Http\Client\Response;
use Orbit\Sdk\Exceptions\ConnectionException;
use Orbit\Sdk\Exceptions\RequestException;

abstract readonly class Resource
{
    public function __construct(
        protected PendingRequest $http,
    ) {}

    /**
     * @param  Closure(): Response  $request
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     */
    protected function send(Closure $request): Response
    {
        try {
            return $request()->throw();
        } catch (\Illuminate\Http\Client\RequestException $e) {
            throw new RequestException($e->response);
        } catch (\Illuminate\Http\Client\ConnectionException $e) {
            throw new ConnectionException($e->getMessage(), $e->getCode(), $e);
        }
    }
}
