<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Resources;

use Illuminate\Http\Client\Response;
use Orbit\Sdk\Cast;
use Orbit\Sdk\Dto\TelemetrySnapshotResponse;
use Orbit\Sdk\Dto\UsageReport;
use Orbit\Sdk\Exceptions\ConnectionException;
use Orbit\Sdk\Exceptions\RequestException;
use Orbit\Sdk\Exceptions\UnexpectedResponseException;

final readonly class TelemetryResource extends Resource
{
    /**
     * Current telemetry snapshot for a beacon
     *
     * GET /beacons/{id}/telemetry
     *
     * @param  int  $id  Beacon id
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function telemetrySnapshot(int $id): TelemetrySnapshotResponse
    {
        $response = $this->send(fn (): Response => $this->http->get('/beacons/'.$id.'/telemetry'));

        return TelemetrySnapshotResponse::fromArray(Cast::toArray($response->json(), 'telemetrySnapshot response'));
    }

    /**
     * Message usage totals for a beacon
     *
     * GET /beacons/{id}/usage
     *
     * @param  int  $id  Beacon id
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function beaconUsage(int $id): UsageReport
    {
        $response = $this->send(fn (): Response => $this->http->get('/beacons/'.$id.'/usage'));

        return UsageReport::fromArray(Cast::toArray($response->json(), 'beaconUsage response'));
    }
}
