<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Testing;

use Gizmo\Sdk\Dto\Assembly;
use Gizmo\Sdk\Dto\Widget;
use Gizmo\Sdk\Dto\WidgetAlert;

/**
 * Test data factories and Http::fake URL patterns for the Gizmo SDK.
 *
 * Factory arrays use wire keys and are seeded from the spec's example values;
 * pass overrides with wire keys: GizmoFake::widget(['field' => ...]).
 */
final class GizmoFake
{
    /** GET /assemblies */
    public const LIST_ASSEMBLIES = '*/assemblies';

    /** GET /widgets/search */
    public const SEARCH_WIDGETS = '*/widgets/search';

    /** GET /widgets/{sn} */
    public const GET_WIDGET = '*/widgets/*';

    /** PATCH /widgets/{sn} */
    public const UPDATE_WIDGET = '*/widgets/*';

    /** GET /widgets/{sn}/alerts */
    public const LIST_WIDGET_ALERTS = '*/widgets/*/alerts';

    /** POST /widgets/{sn}/ping */
    public const PING_WIDGET = '*/widgets/*/ping';

    /**
     * Wire array for Widget.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function widget(array $overrides = []): array
    {
        return array_replace([
            '__rec_WidgetSN' => 40213,
            'calc_AssemblyCodeID' => 'ASM-204',
            'widget_name' => 'Torsion Coupler',
            'bin_location' => 'A-17',
            'built_at' => '2026-03-01T08:30:00Z',
        ], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function widgetDto(array $overrides = []): Widget
    {
        return Widget::fromArray(self::widget($overrides));
    }

    /**
     * Wire array for WidgetAlert.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function widgetAlert(array $overrides = []): array
    {
        return array_replace([
            '__rec_WidgetSN' => 40213,
            'calc_AssemblyCodeID' => 'ASM-204',
            'widget_name' => 'Torsion Coupler',
            'bin_location' => 'A-17',
            'built_at' => '2026-03-01T08:30:00Z',
            'alert_type' => 'overheat',
            'alert_note' => 'alert_note',
            'raised_at' => '2026-01-01T00:00:00+00:00',
        ], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function widgetAlertDto(array $overrides = []): WidgetAlert
    {
        return WidgetAlert::fromArray(self::widgetAlert($overrides));
    }

    /**
     * Wire array for Assembly.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function assembly(array $overrides = []): array
    {
        return array_replace(['__rec_AssemblySN' => 7, 'assembly_name' => 'Coupler Line', 'station_count' => 1], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function assemblyDto(array $overrides = []): Assembly
    {
        return Assembly::fromArray(self::assembly($overrides));
    }
}
