<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Exceptions;

/**
 * Transport failure talking to the Gizmo API (DNS, timeout, refused connection).
 */
final class ConnectionException extends \Illuminate\Http\Client\ConnectionException implements GizmoException {}
