<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Exceptions;

/**
 * Marker for every exception the Gizmo SDK throws.
 */
interface GizmoException extends \Throwable {}
