<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Exceptions;

use Illuminate\Http\Client\RequestException as BaseRequestException;

/**
 * 4xx/5xx response from the Gizmo API.
 *
 * Extends Illuminate's RequestException, so $e->response and existing catch sites keep working.
 */
final class RequestException extends BaseRequestException implements GizmoException {}
