<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Exceptions;

/**
 * A 2xx response whose body does not match the OpenAPI spec.
 *
 * Thrown by the Cast helpers during hydration.
 */
final class UnexpectedResponseException extends \UnexpectedValueException implements GizmoException {}
