<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk;

use Gizmo\Sdk\Resources\AssembliesResource;
use Gizmo\Sdk\Resources\WidgetsResource;
use Illuminate\Container\Attributes\Config;
use Illuminate\Container\Attributes\Singleton;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;

/**
 * Client for Gizmo Works API (spec version 1.4.0).
 *
 * Resolve via the container — `app(GizmoClient::class)` — to read
 * config('services.gizmo.url'), .api_key, .timeout (seconds) and .retries,
 * or construct explicitly with make() / fromPendingRequest().
 */
#[Singleton]
final class GizmoClient
{
    public const API_KEY_HEADER = 'X-Gizmo-Key';

    private ?PendingRequest $http = null;

    public function __construct(
        #[Config('services.gizmo.url', '')]
        private string $baseUrl = '',
        #[Config('services.gizmo.api_key', null)]
        private ?string $apiKey = null,
        #[Config('services.gizmo.timeout', null)]
        private ?int $timeout = null,
        #[Config('services.gizmo.retries', null)]
        private ?int $retries = null,
    ) {}

    public static function make(
        string $baseUrl,
        ?string $apiKey = null,
        ?int $timeout = null,
        ?int $retries = null,
    ): self {
        return new self($baseUrl, $apiKey, $timeout, $retries);
    }

    /**
     * Bring your own PendingRequest — base URL, auth, middleware, fakes.
     */
    public static function fromPendingRequest(PendingRequest $http): self
    {
        $client = new self;
        $client->http = $http;

        return $client;
    }

    /**
     * The underlying PendingRequest (built lazily from config on first use).
     */
    public function http(): PendingRequest
    {
        if ($this->http !== null) {
            return $this->http;
        }

        $http = Http::baseUrl(rtrim($this->baseUrl, '/'))->acceptJson()->asJson();

        if ($this->apiKey !== null) {
            $http = $http->withHeaders([self::API_KEY_HEADER => $this->apiKey]);
        }

        if ($this->timeout !== null) {
            $http = $http->timeout($this->timeout);
        }

        if ($this->retries !== null) {
            $http = $http->retry($this->retries, 100);
        }

        return $this->http = $http;
    }

    public function assemblies(): AssembliesResource
    {
        return new AssembliesResource($this->http());
    }

    public function widgets(): WidgetsResource
    {
        return new WidgetsResource($this->http());
    }
}
