<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk;

/**
 * Sentinel for "field not provided" in partial-update request DTOs.
 *
 * Distinguishes omitting a field entirely (server leaves it untouched)
 * from sending an explicit null (server clears it).
 */
enum Omitted
{
    case Value;
}
