<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Resources;

use Gizmo\Sdk\Cast;
use Gizmo\Sdk\Dto\Assembly;
use Gizmo\Sdk\Exceptions\ConnectionException;
use Gizmo\Sdk\Exceptions\RequestException;
use Gizmo\Sdk\Exceptions\UnexpectedResponseException;
use Illuminate\Http\Client\Response;
use Illuminate\Support\Collection;

final readonly class AssembliesResource extends Resource
{
    /**
     * List assembly lines
     *
     * GET /assemblies
     *
     * @return Collection<int, Assembly>
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function listAssemblies(): Collection
    {
        $response = $this->send(fn (): Response => $this->http->get('/assemblies'));
        $data = Cast::toList($response->json() ?? [], 'listAssemblies response');

        return (new Collection($data))->map(static fn (mixed $item): Assembly => Assembly::fromArray(Cast::toArray($item, 'listAssemblies response[]')));
    }
}
