<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Resources;

use Closure;
use Gizmo\Sdk\Exceptions\ConnectionException;
use Gizmo\Sdk\Exceptions\RequestException;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Http\Client\Response;

abstract readonly class Resource
{
    public function __construct(
        protected PendingRequest $http,
    ) {}

    /**
     * @param  Closure(): Response  $request
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     */
    protected function send(Closure $request): Response
    {
        try {
            return $request()->throw();
        } catch (\Illuminate\Http\Client\RequestException $e) {
            throw new RequestException($e->response);
        } catch (\Illuminate\Http\Client\ConnectionException $e) {
            throw new ConnectionException($e->getMessage(), $e->getCode(), $e);
        }
    }
}
