<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Gizmo Works API" v1.4.0 (spec 28a560b46fc9).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Gizmo\Sdk\Resources;

use Gizmo\Sdk\Cast;
use Gizmo\Sdk\Dto\Widget;
use Gizmo\Sdk\Dto\WidgetAlert;
use Gizmo\Sdk\Dto\WidgetUpdate;
use Gizmo\Sdk\Exceptions\ConnectionException;
use Gizmo\Sdk\Exceptions\RequestException;
use Gizmo\Sdk\Exceptions\UnexpectedResponseException;
use Illuminate\Http\Client\Response;
use Illuminate\Support\Collection;
use Illuminate\Support\LazyCollection;

final readonly class WidgetsResource extends Resource
{
    /**
     * Search widgets
     *
     * GET /widgets/search
     *
     * @param  string|null  $q  Free-text search over widget names
     * @param  int|null  $offset  Row offset
     * @param  int|null  $limit  Maximum rows to return
     * @return Collection<int, Widget>
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function searchWidgets(?string $q = null, ?int $offset = null, ?int $limit = null): Collection
    {
        $query = array_filter([
            'q' => $q,
            'offset' => $offset,
            'limit' => $limit,
        ], static fn (mixed $value): bool => $value !== null);

        $response = $this->send(fn (): Response => $this->http->get('/widgets/search', $query));
        $data = Cast::toList($response->json() ?? [], 'searchWidgets response');

        return (new Collection($data))->map(static fn (mixed $item): Widget => Widget::fromArray(Cast::toArray($item, 'searchWidgets response[]')));
    }

    /**
     * Auto-paging variant of searchWidgets() — iterates every row,
     * fetching $chunkSize per request. Requests are made lazily during iteration.
     *
     * @param  string|null  $q  Free-text search over widget names
     * @return LazyCollection<int, Widget>
     */
    public function searchWidgetsLazy(?string $q = null, int $chunkSize = 500): LazyCollection
    {
        return LazyCollection::make(function () use ($q, $chunkSize): \Generator {
            $offset = 0;

            do {
                $page = $this->searchWidgets(q: $q, offset: $offset, limit: $chunkSize);

                foreach ($page as $item) {
                    yield $item;
                }

                $offset += $chunkSize;
            } while ($page->count() === $chunkSize);
        });
    }

    /**
     * Fetch a widget by serial number
     *
     * GET /widgets/{sn}
     *
     * @param  int  $sn  Widget serial number
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function getWidget(int $sn): Widget
    {
        $response = $this->send(fn (): Response => $this->http->get('/widgets/'.$sn));

        return Widget::fromArray(Cast::toArray($response->json(), 'getWidget response'));
    }

    /**
     * Partially update a widget
     *
     * PATCH /widgets/{sn}
     *
     * @param  int  $sn  Widget serial number
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function updateWidget(int $sn, WidgetUpdate $body): Widget
    {
        $response = $this->send(fn (): Response => $this->http->patch('/widgets/'.$sn, $body->jsonSerialize()));

        return Widget::fromArray(Cast::toArray($response->json(), 'updateWidget response'));
    }

    /**
     * List alerts raised by a widget
     *
     * GET /widgets/{sn}/alerts
     *
     * @param  int  $sn  Widget serial number
     * @return Collection<int, WidgetAlert>
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     * @throws UnexpectedResponseException when the response defies the spec
     */
    public function listWidgetAlerts(int $sn): Collection
    {
        $response = $this->send(fn (): Response => $this->http->get('/widgets/'.$sn.'/alerts'));
        $data = Cast::toList($response->json() ?? [], 'listWidgetAlerts response');

        return (new Collection($data))->map(static fn (mixed $item): WidgetAlert => WidgetAlert::fromArray(Cast::toArray($item, 'listWidgetAlerts response[]')));
    }

    /**
     * Ping a widget's controller
     *
     * POST /widgets/{sn}/ping
     *
     * @param  int  $sn  Widget serial number
     *
     * @throws ConnectionException on transport errors
     * @throws RequestException on 4xx/5xx responses
     */
    public function pingWidget(int $sn): mixed
    {
        $response = $this->send(fn (): Response => $this->http->post('/widgets/'.$sn.'/ping'));

        return $response->json();
    }
}
