<?php

declare(strict_types=1);

namespace NovaHorizons\SdkGenerator;

use Illuminate\Support\Str;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use NovaHorizons\SdkGenerator\Emitter\ClientEmitter;
use NovaHorizons\SdkGenerator\Emitter\DtoEmitter;
use NovaHorizons\SdkGenerator\Emitter\EnumEmitter;
use NovaHorizons\SdkGenerator\Emitter\Expressions;
use NovaHorizons\SdkGenerator\Emitter\OmittedEmitter;
use NovaHorizons\SdkGenerator\Emitter\ResourceEmitter;
use NovaHorizons\SdkGenerator\Emitter\Types;

final class GenerationResult
{
    /**
     * @param  list<string>  $files
     * @param  list<string>  $warnings
     */
    public function __construct(
        public array $files,
        public array $warnings,
        public string $clientClass = '',
        /** The config key the generated client reads, e.g. "services.orbit". */
        public string $configKey = '',
    ) {}
}

final readonly class Generator
{
    public function __construct(private Config $config) {}

    public function generate(): GenerationResult
    {
        $spec = SpecLoader::load($this->config->specPath);

        $mapper = new Mapper($this->config);
        $api = $mapper->map($spec);

        if ($mapper->violations !== []) {
            throw new SpecViolationsException($mapper->violations);
        }

        $ns = $this->config->namespace;
        $types = new Types($ns);
        $expressions = new Expressions($types);

        $clientClass = $this->config->clientClass
            ?? Names::className($api->title).'Client';

        $files = [];

        $brand = preg_replace('/Client$/', '', $clientClass) ?: $clientClass;
        $configKey = $this->config->configKey ?? 'services.'.Str::snake($brand);

        // Client
        $files[$clientClass.'.php'] = (new ClientEmitter($ns, $clientClass, $this->config->defaultApiKeyHeader, $configKey))->emit($api);

        // Testing support
        $files['Testing/'.$brand.'Fake.php'] = (new Emitter\FakeEmitter($ns, $brand, $types))->emit($api);

        // SDK README (raw markdown, not a PhpFile)
        $rawFiles = [
            'README.md' => (new Emitter\ReadmeEmitter($ns, $clientClass, $brand, $configKey, $types))->emit($api),
        ];

        // Support classes
        foreach ((new Emitter\ExceptionsEmitter($ns, $brand, $types))->emit($api) as $path => $file) {
            $files[$path] = $file;
        }
        $files['Resources/Resource.php'] = (new Emitter\ResourceBaseEmitter($ns))->emit();
        $files['Cast.php'] = (new Emitter\CastEmitter($ns))->emit();

        if ($api->needsOmitted()) {
            $files['Omitted.php'] = (new OmittedEmitter($ns))->emit();
        }

        // DTOs
        $dtoEmitter = new DtoEmitter($ns, $types, $expressions);
        foreach ($api->objects as $object) {
            $files['Dto/'.$object->className.'.php'] = $dtoEmitter->emit($object);
        }

        // Enums
        $enumEmitter = new EnumEmitter($ns);
        foreach ($api->enums as $enum) {
            $files['Enums/'.$enum->className.'.php'] = $enumEmitter->emit($enum);
        }

        // Resources
        $resourceEmitter = new ResourceEmitter($ns, $types);
        foreach ($api->resources as $resourceName => $operations) {
            $files['Resources/'.$resourceName.'Resource.php'] = $resourceEmitter->emit($resourceName, $operations);
        }

        $written = [];
        $printer = new PsrPrinter;

        $specHash = substr(md5((string) file_get_contents($this->config->specPath)), 0, 12);

        foreach ($files as $relativePath => $file) {
            $this->stampGenerated($file, $api->title, $api->version, $specHash);
            $this->write($relativePath, $printer->printFile($file));
            $written[] = $relativePath;
        }

        foreach ($rawFiles as $relativePath => $contents) {
            $this->write($relativePath, $contents);
            $written[] = $relativePath;
        }

        return new GenerationResult($written, $mapper->warnings, $clientClass, $configKey);
    }

    private function write(string $relativePath, string $contents): void
    {
        $absolute = rtrim($this->config->outputDir, '/').'/'.$relativePath;
        $dir = dirname($absolute);
        if (! is_dir($dir) && ! mkdir($dir, 0755, true) && ! is_dir($dir)) {
            throw new \RuntimeException("Could not create directory: {$dir}");
        }

        file_put_contents($absolute, $contents);
    }

    private function stampGenerated(PhpFile $file, string $title, string $version, string $specHash): void
    {
        $file->addComment("@generated by nova-horizons/laravel-openapi-sdk-generator from \"{$title}\" v{$version} (spec {$specHash}).");
        $file->addComment('Do not edit — changes will be overwritten on the next generation.');
    }
}
