<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Testing;

use Orbit\Sdk\Dto\Beacon;
use Orbit\Sdk\Dto\Error;
use Orbit\Sdk\Dto\GeoFix;
use Orbit\Sdk\Dto\TelemetrySnapshotResponse;
use Orbit\Sdk\Dto\TelemetrySnapshotResponseSignal;
use Orbit\Sdk\Dto\UsageReport;

/**
 * Test data factories and Http::fake URL patterns for the Orbit SDK.
 *
 * Factory arrays use wire keys and are seeded from the spec's example values;
 * pass overrides with wire keys: OrbitFake::error(['field' => ...]).
 *
 * Http::fake() matches URL patterns only — it never sees the HTTP method. Two
 * operations on the same path (list vs create) share an identical pattern, and a
 * wildcard pattern also matches deeper routes. Register more specific patterns
 * first, and branch on $request->method() in a fake closure when operations share
 * a URL.
 */
final class OrbitFake
{
    /** GET /beacons */
    public const LIST_BEACONS = '*/beacons';

    /** POST /beacons */
    public const CREATE_BEACON = '*/beacons';

    /** GET /beacons/{id} */
    public const GET_BEACON = '*/beacons/*';

    /** GET /beacons/{id}/telemetry */
    public const TELEMETRY_SNAPSHOT = '*/beacons/*/telemetry';

    /** GET /beacons/{id}/usage */
    public const BEACON_USAGE = '*/beacons/*/usage';

    /**
     * Wire array for Error.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function error(array $overrides = []): array
    {
        return array_replace(['code' => 'not_found', 'message' => 'No beacon with that id'], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function errorDto(array $overrides = []): Error
    {
        return Error::fromArray(self::error($overrides));
    }

    /**
     * Wire array for Beacon.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function beacon(array $overrides = []): array
    {
        return array_replace([
            'id' => 12,
            'callsign' => 'AURORA-7',
            'active' => true,
            'launched_at' => '2025-11-05T14:20:00Z',
            'last_fix' => ['lat' => -41.29, 'lon' => 174.78],
        ], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function beaconDto(array $overrides = []): Beacon
    {
        return Beacon::fromArray(self::beacon($overrides));
    }

    /**
     * Wire array for GeoFix.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function geoFix(array $overrides = []): array
    {
        return array_replace(['lat' => -41.29, 'lon' => 174.78], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function geoFixDto(array $overrides = []): GeoFix
    {
        return GeoFix::fromArray(self::geoFix($overrides));
    }

    /**
     * Wire array for UsageReport.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function usageReport(array $overrides = []): array
    {
        return array_replace(['total' => 3120, 'counts' => ['telemetry' => 2900, 'commands' => 220]], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function usageReportDto(array $overrides = []): UsageReport
    {
        return UsageReport::fromArray(self::usageReport($overrides));
    }

    /**
     * Wire array for TelemetrySnapshotResponse.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function telemetrySnapshotResponse(array $overrides = []): array
    {
        return array_replace([
            'sampled_at' => '2026-02-10T09:00:00Z',
            'battery_pct' => 87.5,
            'signal' => ['strength_db' => -71.5, 'locked' => true],
        ], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function telemetrySnapshotResponseDto(array $overrides = []): TelemetrySnapshotResponse
    {
        return TelemetrySnapshotResponse::fromArray(self::telemetrySnapshotResponse($overrides));
    }

    /**
     * Wire array for TelemetrySnapshotResponseSignal.
     *
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     * @return array<string, mixed>
     */
    public static function telemetrySnapshotResponseSignal(array $overrides = []): array
    {
        return array_replace(['strength_db' => -71.5, 'locked' => true], $overrides);
    }

    /**
     * @param  array<string, mixed>  $overrides  wire-keyed values to replace
     */
    public static function telemetrySnapshotResponseSignalDto(array $overrides = []): TelemetrySnapshotResponseSignal
    {
        return TelemetrySnapshotResponseSignal::fromArray(self::telemetrySnapshotResponseSignal($overrides));
    }
}
