<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Exceptions;

/**
 * The Orbit client is missing required setup (e.g. no base URL).
 *
 * A deployment/wiring problem, not an API failure — fix the config rather than catching this.
 */
final class ConfigurationException extends \LogicException implements OrbitException {}
