<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Exceptions;

/**
 * Transport failure talking to the Orbit API (DNS, timeout, refused connection).
 */
final class ConnectionException extends \Illuminate\Http\Client\ConnectionException implements OrbitException {}
