<?php

/**
 * @generated by nova-horizons/laravel-openapi-sdk-generator from "Orbit" v2.0.0 (spec f1c0be706599).
 * Do not edit — changes will be overwritten on the next generation.
 */

declare(strict_types=1);

namespace Orbit\Sdk\Exceptions;

use Illuminate\Http\Client\RequestException as BaseRequestException;
use Orbit\Sdk\Dto\Error;

/**
 * 4xx/5xx response from the Orbit API.
 *
 * Extends Illuminate's RequestException, so $e->response and existing catch sites keep working.
 */
final class RequestException extends BaseRequestException implements OrbitException
{
    /**
     * The API error body, when it matches the documented error schema.
     */
    public function error(): ?Error
    {
        try {
            $data = $this->response->json();

            return is_array($data) ? Error::fromArray($data) : null;
        } catch (UnexpectedResponseException) {
            return null;
        }
    }
}
